Ejercicio 1
Corte0/ASYS-TP3 pull request #1
Opened 2024-09-18 01:44 UTC by Corte0

2024-09-18 18:41 UTC, ffpp2003 commented on images/ej1..4png
Qesesto?

2024-09-18 18:42 UTC, ffpp2003 commented on images/ej1..4png
Corregí el formato

2024-09-18 18:43 UTC, fpp3 requested changes
Corregir el formato de las imagenes

2024-09-18 18:43 UTC, fpp3 commented on images/ej1.4png
Corregí el formato

2024-09-18 18:43 UTC, fpp3 commented on images/ej1..4png
Corregí el formato

2024-09-19 02:00 UTC, ffpp2003 approved these changes

2024-09-19 02:01 UTC, merged